### ISSUE TITLE
exploit dosent work/patched

### ISSUE THREAD

**Issue by deyeezy** [zek-c/Securly-Kill-V111#47]
The insecurely exploit is patched since my school changed the securely version and extension ID, they forced install by not using the Chrome web store, and the ID is "knneimmpeamikmjijmnhjmmobddleohj"

If you don't want to make a patch for my school @zek-c 
how can I create an HTML file with the cookie to corrupt securely's cookies

**Comment by zek-c** [comment]
ok so insecurly is slowly getting patched out and i am NOT making a patch. an html file can't run the cookie corrupter because javascript doesn't allow a different tab to set a cookie for a different URL. you have to be able to run javascript on securly.com. skiovox is also getting patched out, so you'll have to wait it out. you can also use the terminal exploit which i will post here maybe in a while but im lazy rn cus it's winter break

**Comment by deyeezy** [comment]
The JavaScript dosent work for me since it dosent do anything on
securely.com

Although how can you create the cookie though, since I’m thinking to make
it by using code pen

**Comment by zek-c** [comment]
the javascript doesn't do anything because javascript bookmarklets and URL running is disabled after V116. making a cookie is easy, just `document.cookie =${parameters};`

**Comment by deyeezy** [comment]
Then how did you made the currupted cookies?

**Comment by zek-c** [comment]
it just replaces securlys current cookies with false cookies that don't actively search for blocked sites and blocks the cdn n stuff and corrupts the connection.

**Comment by dekid69** [comment]
@zek-c yea i know how that works, but how did you create the currupted cookies, did you use a converter or something?

**Comment by zek-c** [comment]
uh no i gave it bad attributes and malbytes, messes with securlys functions

**Comment by dekid69** [comment]
@zek-c then how did you convert that into a cookie?

**Comment by zek-c** [comment]
by giving the attributes to the cookie, a cookie is just javascript that runs every time you open a page so just set the cookie withthe attributes with `document.cookie='{attributes here}'`
